# Generated by Django 4.1.2 on 2022-10-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="price",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
